name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          manifest: .github/labels.yml
          repository: |
              CyclopsMC/CyclopsCore
              CyclopsMC/Flopper
              CyclopsMC/StructuredCrafting
              CyclopsMC/CapabilityProxy
              CyclopsMC/CommonCapabilities
              CyclopsMC/EverlastingAbilities
              CyclopsMC/EnergeticSheep
              CyclopsMC/ColossalChests
              CyclopsMC/IconExporter
              CyclopsMC/IntegratedDynamics
              CyclopsMC/IntegratedDynamics-Compat
              CyclopsMC/EvilCraft
              CyclopsMC/EvilCraft-Compat
              CyclopsMC/IntegratedTunnels
              CyclopsMC/IntegratedTunnels-Compat
              CyclopsMC/IntegratedCrafting
              CyclopsMC/IntegratedTerminals
              CyclopsMC/IntegratedTerminals-Compat
              CyclopsMC/IntegratedREST
              CyclopsMC/IntegratedScripting
          token: ${{ secrets.PAT }}
